# Site settings
title: Divya Prakash Mittal
description: 'Programming, Quizzing, Science and Open-source'
url: 'dpmittal.me'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'dpmittal'

author:
  name: 'Divya Prakash Mittal'
  email: divyaprakashmittal@gmail.com
  twitter_username: imdpmittal
  facebook_username: divya.prakashmittal
  github_username:  dpmittal
  linkedin_username:  dpmittal

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
