# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title: Divya Prakash Mittal
description: 'Open-Source lover trying to build things'
url: 'dpmittal.me'
disqus:
  shortname: 'dpmittal'
baseurl:          ''


author:
  name: 'Divya Prakash Mittal'
  email: divyaprakashmittal@gmail.com
  github_username:  dpmittal
  linkedin_username:  dpmittal

paginate:         5
paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
sidebar_home_link:  true
sidebar_blog_link:  '/blog'
